services:
  mongodb:
    image: mongo:${MONGODB_VERSION}
    networks:
      - envoii

  postgres:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - envoii

  s3:
    image: minio/minio:${MINIO_VERSION}
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9000:9000"
    networks:
      - envoii

networks:
  envoii:
    driver: bridge
